project_id = "thxlbfxlvckjsmebnfsx"

[functions.mercadopago-webhook]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.delete-cancelled-order]
verify_jwt = false
