// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search Art & Personalizados products by keyword. Returns id, name, slug, price, category and short description.",
  inputSchema: {
    query: z.string().trim().default("").describe("Optional search text; empty returns featured/newest."),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("products").select("id,name,slug,price,old_price,description,image,category_id,badge,featured,active").eq("active", true).limit(limit);
    if (query && query.length > 0) {
      q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    } else {
      q = q.order("featured", { ascending: false }).order("created_at", { ascending: false });
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch a single product by slug, including full description, gallery and variants.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("The product slug (URL segment).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const supabase = supabaseForUser2(ctx);
    const { data: product, error } = await supabase.from("products").select("*, product_variants(label, options, sort_order)").eq("slug", slug).eq("active", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!product) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(product) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all active product categories of the Art & Personalizados catalog.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("categories").select("id,name,slug,description,icon,sort_order").eq("active", true).order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's orders (order number, status, total, dates). Row-level security ensures only the caller's own orders are returned.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("orders").select("id,order_number,status,total,subtotal,shipping_cost,payment_method,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-order.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_order_default = defineTool5({
  name: "get_my_order",
  title: "Get my order",
  description: "Fetch full details of one of the signed-in user's orders by order number, including items and shipping address.",
  inputSchema: {
    order_number: z4.number().int().positive().describe("The public order number (e.g. 1001).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const { data: order, error } = await supabase.from("orders").select("*, order_items(product_name,variant,quantity,unit_price,subtotal,product_image)").eq("user_id", ctx.getUserId()).eq("order_number", order_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!order) return { content: [{ type: "text", text: "Order not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(order) }],
      structuredContent: { order }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "thxlbfxlvckjsmebnfsx";
var mcp_default = defineMcp({
  name: "art-personalizados-mcp",
  title: "Art & Personalizados",
  version: "0.1.0",
  instructions: "Tools for the Art & Personalizados online store. Use `search_products`, `get_product` and `list_categories` to browse the catalog. Use `list_my_orders` and `get_my_order` to look up the signed-in customer's orders (row-level security scopes results to that user).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_categories_default, list_my_orders_default, get_my_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
